### ISSUE TITLE
Include area as sensor attribute.

### ISSUE THREAD

**Issue by C4-Dimitri** [pantherale0/ha-fuelprices#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently it is impossible to filter the sensors created by the area that was defined that included them.

### Describe the solution you'd like

Include the area as an attribute of the created sensor.

### Describe alternatives you've considered

allow multiple services to be created for different areas

### Additional context

Realise that the attribute solution may have problems when sensors are created from overlapping areas.

**Comment by pantherale0** [comment]
Hi,

This would be difficult to implement at the moment, will require some changes in the module as the area is not passed into search queries.

**Comment by pantherale0** [comment]
Added for next release

![image](https://github.com/pantherale0/ha-fuelprices/assets/7346615/e2d18f73-1c3b-4be1-8125-430fad3809ef)
