### ISSUE TITLE
UK Fuel Prices have an incorrect unit

### ISSUE THREAD

**Issue by pantherale0** [pantherale0/ha-fuelprices#16]
Fuel prices for UK data sources currently show an incorrect unit of GBP when the value is actually in pence.

Example of GasBuddy with correct unit:

![image](https://github.com/pantherale0/ha-fuelprices/assets/7346615/0dd88ce9-40b8-4b40-93c9-64db38856305)

Example of a UK Fuel station:

![image](https://github.com/pantherale0/ha-fuelprices/assets/7346615/ad268121-e37d-4656-860a-2aec4413a9bc)

**Comment by trentnbauer** [comment]
I also have PetrolSpy in Australia showing NZD, not AUD

**Comment by pantherale0** [comment]
My bad, I have it hard-coded to NZD for some reason. I will fix this for next update.

**Comment by pantherale0** [comment]
Fixed 2024.10.0
