### ISSUE TITLE
Support for government fuel price API in Queensland,Australia

### ISSUE THREAD

**Issue by mihalski** [pantherale0/ha-fuelprices#20]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The canonical source of fuel prices in Queensland, Australia is the API described at https://www.fuelpricesqld.com.au/ and this will always provide the most accurate and current prices available.

### Describe the solution you'd like

Support for the https://www.fuelpricesqld.com.au/ API.

### Describe alternatives you've considered

This problem does not lend itself to an alternative. I currently use an IOS app called Petty which accesses this information.

### Additional context

Scraped data from the listed apps lags behind the API considerably and I would like to create automations which notify me of good prices close to where I am or to monitor particular petrol stations and send me notifications when the prices drop.

**Comment by pantherale0** [comment]
Hi,

As this requires an API token to interact with, its not something I will look at immediately, but will be added for future consideration.

Thanks

**Comment by pantherale0** [comment]
Linking related issue - https://github.com/pantherale0/pyfuelprices/issues/9

**Comment by pantherale0** [comment]
This isn't possible, not because of the API token, but because I'm in the UK and therefore the dataset isn't available to allow me to register. Plus there appears to be a cost of some description? (At least according to the API).
