### ISSUE TITLE
Australia WA Fuel Watch - Tomorrow Price

### ISSUE THREAD

**Issue by alwyntn** [pantherale0/ha-fuelprices#21]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It is not a problem.

### Describe the solution you'd like

Daily at around 2:30pm WA local time, fuelwatch WA will update tomorrow fuel price. Would be nice if can retrieve the price feed too.

### Describe alternatives you've considered

Unable to think of anything

### Additional context

nil

**Comment by pantherale0** [comment]
Very difficult for me to implement due to the timezone difference. For me, 2:30pm in WA is around 7:30am and I'm not usually up at this time. I will work on this as soon as I can, but no guarantees

**Comment by pantherale0** [comment]
I've taken a look at this, and actually I think the data should already be there under the entity attributes. I _think_ something like:
`available_fuels.<fuel>.props.tomrrowPrice`

I'll double check for you though :)

**Comment by pantherale0** [comment]
Implemented a new key for this in 2024.10.0.

`fuel_details.<FUEL_CODE>.priceTomorrow`

If `priceTomorrow` is not available, that is because it is not available in the API.
