### ISSUE TITLE
Fuel prices, too many numbers after decimal point

### ISSUE THREAD

**Issue by marc115uk** [pantherale0/ha-fuelprices#24]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1518
Downloaded Repositories | 74

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 326.1 GB
disk_used | 262.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), MariaDB (2.7.1), RPC Shutdown (2.5), Samba share (12.3.2), ESPHome (2024.10.0), Zigbee2MQTT (1.40.2-1), Grafana (10.1.3), InfluxDB (5.0.1), Log Viewer (0.17.1), phpMyAdmin (0.10.0), Advanced SSH & Web Terminal (19.0.0), Git pull (7.14.1), AirCast (4.2.2), eWeLink Smart Home (1.4.3), Samba Backup (5.2.0), EMQX (0.7.1), Studio Code Server (5.17.2), PS5 MQTT (1.4.0), ZigStar TI CC2652P/P7 FW Flasher (0.4.1), Node-RED (18.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 58
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 11, 2024 at 11:28 PM
-- | --
current_recorder_run | October 20, 2024 at 1:14 AM
estimated_db_size | 3479.33 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since latest update, fuel prices are sometimes showing multiple numbers after decimal point. Before it showed 3 numbers, now most of the time it shows 3 however on some sensors it shows lots of numbers i.e, E5: 1.5190000000000001 should ideally display as 1.519

state_class: total
id: bpuk_gcpgh3ngjmpr
name: BP RH6 0NN
address: Ring Road North (A23)
postal_code: RH6 0NN
latitude: 51.15838
longitude: -0.15529
brand: BP
available_fuels: 
E5: 1.5190000000000001
E10: 1.339
B7: 1.379
SDV: 1.5390000000000001

fuel_details: 
E5: {}
E10: {}
B7: {}
SDV: {}

currency: GBP
last_updated: 2024-10-20T01:14:34.690025
next_update: 2024-10-21T01:14:38.301238
props: 
source: bpuk
source_id: gcpgh3ngjmpr
prevent_cache_cleanup: true

E5: 1.5190000000000001
E10: 1.339
B7: 1.379
SDV: 1.5390000000000001
area: Home
unit_of_measurement: GBP
icon: mdi:gas-station
friendly_name: BP RH6 0NN****

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

**Comment by pantherale0** [comment]
Hi,

This isn't a problem with the integration, but instead the fuel data source. I've seen it myself a few times.

In this case there is a problem on BP's side.

Thanks
