### ISSUE TITLE
2024.1.0b0 - warnings in logs for gasbuddy

### ISSUE THREAD

**Issue by pantherale0** [pantherale0/ha-fuelprices#5]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Gasbuddy logs warnings during update hook when an area is not within USA

### Reproduction steps

1. Setup integration
2. Wait for updater to execute

### Debug logs

```text
Logger: pyfuelprices.sources.usa.gasbuddy
Source: runner.py:188
First occurred: 5 January 2024 at 23:26:55 (72 occurrences)
Last logged: 10:27:23

Ignoring area {'radius': 5.0, 'lat': 53.068464, 'long': 12.532709} as it is not found in USA.
Ignoring area {'radius': 5.0, 'lat': -31.994327, 'long': 115.930681} as it is not found in USA.
Ignoring area {'radius': 5.0, 'lat': 52.23817, 'long': 6.58763} as it is not found in USA.
```

**Comment by poudenes** [comment]
I had same issue. Did you forgotten to give a "source" in your configuration. I was forgotten that.

**Comment by pantherale0** [comment]
> I had same issue. Did you forgotten to give a "source" in your configuration. I was forgotten that.

Thanks, I know where the "problem" is, the GasBuddy source does intentionally log these warnings in the data provider so I just need to remove this line of code (and the next two afterwards).

https://github.com/pantherale0/pyfuelprices/blob/02f92978d2a47c6d05e02fc89e0b20f857ef9f3a/pyfuelprices/sources/usa/gasbuddy.py#L121
